spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      username: spring_cloud_user
      password: ENC(mSn13kz4jq4T8AjFgCE1SJdc810z2/W5otyN6/UQZj+zWRyTNKTo+fwuE+fOmxDvmSo7Exw6PIcS9AFVtyyJGA==)
  config:
    import: "configserver:http://localhost:8888"

jasypt:
  encryptor:
    password: Demo_Pwd!2020