server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArunaDon/spring-cloud-config-server-repository
          username: arunadon
          password:
          clone-on-start: true
      bootstrap: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password:

jasypt:
  encryptor:
    password: Demo_Pwd!2020


